const {test} = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const home = fs.readFileSync('dist/index.html', 'utf8')
const text = (html) => html.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim()
const cards = [...home.matchAll(/<article class="quote-card(?: quote-card-featured)?">([\s\S]*?)<\/article>/g)].map((match) => match[1])

test('window comparison shows two sourced complete-window prices in AUD without naming the overseas supplier', () => {
  assert.equal(cards.length, 2)
  assert.deepEqual(cards.map((card) => card.match(/<h3>(.*?)<\/h3>/)[1]), ['Thai sourcing reference', 'Stegbar'])
  assert.match(cards[0], /THAILAND/)
  assert.match(cards[1], /AUSTRALIA/)
  assert.match(home, /window-comparison--pair/)
  assert.match(home, /Complete aluminium sliding windows · single glazing · qty 1/)
  assert.equal((3690 / 23.57).toFixed(2), '156.55')
  assert.match(cards[0], /<strong>A\$156\.55<\/strong>/)
  assert.match(cards[1], /<strong>A\$742\.50<\/strong>/)
  assert.match(home, /23\.57 THB per AUD/)
  assert.match(home, /RBA reference rate dated 23 Sep 2026/)
  assert.match(cards[0], /href="https:\/\/windowasia\.com\/en\/product\/aluminum-sliding-window-white-s-s-120x110-en\/"/)
  assert.match(cards[1], /href="https:\/\/www\.stegbar\.com\.au\/products\/sliding-window-2-0\?variant=51662968160487"/)
  assert.match(cards[1], /href="https:\/\/www\.stegbar\.com\.au\/pages\/shop-online-support-centre"/)
  assert.doesNotMatch(text(home), /Superhouse|SMG Glass|Window Asia|uPVC\.com\.au|A\$1,126\.44|A\$212–403/)
  assert.doesNotMatch(cards.join(''), /(?:US\$|USD\s*\d|THB\s*\d|฿)/)
})

test('comparison aligns cost categories while retaining different specifications and unresolved Thai costs', () => {
  const labels = cards.map((card) => [...card.matchAll(/<dt>(.*?)<\/dt>/g)].map((match) => text(match[1])))
  assert.deepEqual(labels[0], labels[1], 'both cards use the same scope and cost categories')
  assert.deepEqual(labels[0], [
    'Window / frame', 'Size (W × H)', 'Glass', 'Finish', 'Australian GST',
    'Import / clearance', 'Australian door delivery', 'Installation', 'FABINT service fee',
  ])
  assert.match(cards[0], /1200 × 1100 mm/)
  assert.match(cards[0], /5 mm green-tinted · single/)
  assert.match(cards[1], /1210 × 1200 mm/)
  assert.match(cards[1], /Clear · single<br>Thickness not published/)
  for (const label of ['Australian GST', 'Import / clearance', 'Australian door delivery']) {
    assert.ok(cards[0].includes(`<dt>${label}</dt><dd>Unconfirmed · not priced</dd>`), `Thai ${label} is not invented or treated as free`)
  }
  assert.match(cards[0], /PRODUCT PRICE ONLY/)
  assert.match(cards[0], /Quote required/)
  assert.match(cards[0], /Australian shipping, import costs and our service fee are not included/)
  assert.match(cards[1], /<dt>Australian GST<\/dt><dd>Included<\/dd>/)
  assert.match(cards[1], /<dt>Australian door delivery<\/dt><dd>Included · eligible areas only<\/dd>/)
  assert.match(cards[1], /<dt>Installation<\/dt><dd>Excluded · arrange separately<\/dd>/)
  assert.match(cards[1], /Check your postcode/)
})

test('reference prices are not advertised as a confirmed FABINT offer or verified delivered savings', () => {
  const copy = text(home)
  assert.match(copy, /public listing references, not like-for-like Australian delivered totals or a confirmed FABINT offer/)
  assert.match(copy, /The price gap is not a verified saving/)
  assert.match(copy, /equal quality or Australian suitability has not been established/)
  assert.match(copy, /Unknown costs are not zero/)
  assert.match(copy, /10% of the delivered cost when an order proceeds, waived for our first 10 projects/)
  assert.match(copy, /Thai delivered cost is unknown, no final service fee or FABINT selling price is calculated/)
  assert.match(cards[0], /Not a confirmed supply arrangement/)
  assert.match(cards[0], /does not establish Australian availability, warranty support or certification/)
  assert.doesNotMatch(copy, /save\s+(?:\d+(?:\.\d+)?%|A\$[\d,]+)|\d+(?:\.\d+)?%\s+(?:cheaper|saving|less)/i)
})
