const {test} = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const home = fs.readFileSync('dist/index.html', 'utf8')

test('window comparison aligns the glass brief without inventing matched delivered prices', () => {
  assert.match(home, /6 mm Low-E \/ 12 mm cavity \/ 6 mm toughened double glazing/)
  assert.match(home, /A\$900\/m² × 1\.44 m²/)
  assert.equal((800 / 0.7102).toFixed(2), '1126.44')
  assert.match(home, /Includes freight to Florida, not Australia/)
  assert.match(home, /Interstate quote required/)
  assert.match(home, /Not an exact unit quote/)
  assert.doesNotMatch(home, /US\$800|Stegbar|Melbourne market/)
  const cards = [...home.matchAll(/<article class="quote-card">([\s\S]*?)<\/article>/g)].map((match) => match[1])
  assert.equal(cards.length, 3)
  const labels = cards.map((card) => [...card.matchAll(/<dt>(.*?)<\/dt>/g)].map((match) => match[1]))
  assert.deepEqual(labels[0], labels[1])
  assert.deepEqual(labels[1], labels[2])
})
